name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'dev'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Hello ${{ github.event.inputs.branch }}!"
    - run: "ls"
    - run: 'cat README.md'