on:
  pull_request_review_comment:
    types: created
jobs:
  testing_event:
    name: testevnt
    runs-on: ubuntu-latest
    if: github.event.pull_request_review_comment.comment.body == "PrintMe" 
    steps:
      - name: Testing event
        run: echo 'the print action was triggered! success!'
