name: PR to Dev
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - dev
jobs:
  UnitTest: 
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2#     
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: NPM Install
      run: npm install
    - name: Run UnitTests
      run: npx jest

  Deploy: 
    needs: UnitTest
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2#     
    - run: echo "Using Dev_credentials"
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
# Comment in prod
    - run: sleep 60
    - name: serverless remove
      uses: serverless/github-action@master
      with:
        args: remove
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}