name: Serverless CI Example
on: push
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install 
    - run: npx eslint handler.js 
  
  